### ISSUE TITLE
3.9.1了，希望更新一下

### ISSUE THREAD

**Issue by bulolo** [eggjs-community/egg-wechat-api#14]
3.9.1了，希望更新一下

**Comment by duncup** [comment]
package.json 里面有标记 ^ 前缀，不是主要版本号更新就不会有区别。
参考 [npm 官方文档](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept)

**Comment by bulolo** [comment]
@duncup 好，感谢，还以为小程序接口更新了。

**Comment by duncup** [comment]
这个包只是打包了下模块作为插件载入到egg，如果不是主要版本更新，你本地安装的时候模块就会是最新版本。egg的其他插件通常也是这种模式。
